# NumPy
- NumPy bilimsel hesaplamalar yapabilmek için pratik bir pakettir. Büyük ve çok boyutlu diziler ve matrisler için destek sunar

In [3]:
import numpy as np

## Array Oluşturmak

In [10]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [5]:
type(a)

list

In [8]:
b=list(range(6,11))
b

[6, 7, 8, 9, 10]

In [9]:
a+b  #liste toplama

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### np.array()

In [11]:
a1D = np.array(a)  #List ,np.array tipine dönüştürüldü.

In [12]:
print(a1D)

[1 2 3 4 5]


In [13]:
type(a1D)

numpy.ndarray

In [14]:
b1D = np.array(b)

In [15]:
print(b1D)

[ 6  7  8  9 10]


In [16]:
a1D+b1D  # 1. indeksteki a ve b yi toplayıp verdi, sonra 2. indekstekiler

array([ 7,  9, 11, 13, 15])

In [17]:
a1D-b1D

array([-5, -5, -5, -5, -5])

In [18]:
a1D*b1D

array([ 6, 14, 24, 36, 50])

In [19]:
a1D/b1D

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [20]:
a1D**b1D

array([      1,     128,    6561,  262144, 9765625])

In [21]:
a,b # tupple olarak yazıyor

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

In [22]:
[a,b] #liste içersinde ayrı ayrı a ve b yi listeliyor

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [23]:
a2D=np.array([a,b])

In [24]:
print(a2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
a2D+a2D # her sayıyı birbiri ile topladı

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

## 1D Array Oluşturma Fonksiyonları

### np.arange

In [26]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
np.arange(10)  # 10 da durdurduk stop komutu

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(5,10) #start= 5 stop=9 da durur en son sayı

array([5, 6, 7, 8, 9])

In [29]:
list(range(5,10,2)) # iki sayıda birini soyler. 5 ile başlar

[5, 7, 9]

### np.linspace

In [ ]:
np.linspace() # doc stringi görüntülemek için parantez içerisine shift tuşu ve tab tuşunu kullanırız.

In [ ]:
help(np.linspace)  # yardımı görmek için

In [31]:
np.linspace(0,49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [32]:
np.linspace(5,50, num=10) # on tane sayıyı gösteriyor

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [33]:
np.linspace(5,50, num=21) # 21 tane sayıyı eşit aralıklarla yazmıştır.

array([ 5.  ,  7.25,  9.5 , 11.75, 14.  , 16.25, 18.5 , 20.75, 23.  ,
       25.25, 27.5 , 29.75, 32.  , 34.25, 36.5 , 38.75, 41.  , 43.25,
       45.5 , 47.75, 50.  ])

## 2D Array oluşturma Fonksiyonları

### np.eye

In [34]:
np.eye(5) # birim matris (identy matris)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.eye(6, dtype=int) #veri tipi integer yapar.

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### np.zeros

In [ ]:
np.zeros(5, dtype)

## seed

In [39]:
np.random.seed(2222)
np.random.randn()

-0.9407914639148472

## Arry leri yeniden şekillendirmek

In [41]:
arr=np.arange(1,17)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [42]:
arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
arr=np.arange(10,35)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [45]:
arr[-6:-2]

array([29, 30, 31, 32])

In [51]:
arr= arr.reshape(5,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [47]:
arr[1:3]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr[1:3]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr[2:,3:] #virgül sütun olarak ayırır.

array([[23, 24],
       [28, 29],
       [33, 34]])

# Koşullu Filtreleme

In [65]:
np.random.seed(51)
arr=np.random.randint(0,100, size=50)
print(arr)

[57 96 73 69 16 21 94 52 37 37 60 94 28 84 36 35 27 28 42 10  6 25 33 77
 39 48 24 40 54 77 28 69 57 18 63 75 67 94 87  7 67 91 61 34 53 30 55 17
 67  8]


In [66]:
bool_arr= arr>50  #boolen 50 den büyü sayıları filtreliyor
print(bool_arr)

[ True  True  True  True False False  True  True False False  True  True
 False  True False False False False False False False False False  True
 False False False False  True  True False  True  True False  True  True
  True  True  True False  True  True  True False  True False  True False
  True False]


In [67]:
arr[bool_arr] #50 den büyük sayıları filtreliyor

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [68]:
arr[arr>50]   #50 den büyük olanları filtreler

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [69]:
# bir örnek daha 
arr2=np.array([1,3,4,7,8,9])
bool_arr2=np.array([False, False,True,False,True,False])

In [70]:
len(arr2)

6

In [71]:
arr[bool_arr2]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 50 but corresponding boolean dimension is 6

In [73]:
# bir örnek daha 
np.random.seed(51)
arr3=np.random.randint(125,675,100)
print(arr3)

[182 610 653 561 486 674 153 288 153 551 131 542 586 625 429 149 179 153
 316 200 377 475 596 344 415 562 283 180 654 242 566 266 212 194 366 177
 174 128 403 468 576 634 629 443 544 560 220 602 465 634 433 299 369 172
 209 506 603 484 358 297 565 369 486 549 476 137 580 292 481 562 166 241
 200 208 310 600 127 297 172 533 605 387 414 642 654 279 487 410 326 291
 625 539 386 451 282 396 306 624 495 585]


In [82]:
arr3[(arr3>250) & (arr3<400)]  #250 ile 400 araasındaki sayıları buldu

array([288, 316, 377, 344, 283, 266, 366, 299, 369, 358, 297, 369, 292,
       310, 297, 387, 279, 326, 291, 386, 282, 396, 306])

In [86]:
np.random.seed(51)
arr=np.random.randint(1,101,size=50)
print(arr)

[58 97 74 70 17 22 95 53 38 38 61 95 29 85 37 36 28 29 43 11  7 26 34 78
 40 49 25 41 55 78 29 70 58 19 64 76 68 95 88  8 68 92 62 35 54 31 56 18
 68  9]


In [88]:
arr[arr>25] 

array([58, 97, 74, 70, 95, 53, 38, 38, 61, 95, 29, 85, 37, 36, 28, 29, 43,
       26, 34, 78, 40, 49, 41, 55, 78, 29, 70, 58, 64, 76, 68, 95, 88, 68,
       92, 62, 35, 54, 31, 56, 68])

In [89]:
sum(arr[arr>25])  #25 ten büyük rastgele sayıların toplamı

2381

In [90]:
arr[arr>25].sum() #25 ten büyük rastgele sayıların toplamı

2381

In [91]:
arr[arr>25].mean()  # sayıların ortalamalarını bulur

58.073170731707314

In [92]:
arr[arr>25].std()  # sayıların standart sapmasını bulur

21.76413501321129

In [93]:
arr[arr>25].min()  #sayıların en küçüğünü bulur

26

In [94]:
arr[arr>25].max()  #sayıların en büyüğünü bulur

97

# Numpy Operations

## Aritmetik ortalamalarını 

### mean

In [95]:
np.mean(arr)

50.34

In [96]:
# median
np.median(arr)

51.0

In [ ]:
#std var standart sapma

In [98]:
np.std(arr)

25.839976780175327

In [99]:
arr.var()

667.7044000000001

In [101]:
np.var(arr)

667.7044000000001

In [ ]:
# minimum bulma

In [102]:
np.min(arr)

7

In [103]:
arr.min()

7

In [104]:
arr.max() # maksimum bulma

97

In [105]:
np.max(arr)

97

In [106]:
print(arr)

[58 97 74 70 17 22 95 53 38 38 61 95 29 85 37 36 28 29 43 11  7 26 34 78
 40 49 25 41 55 78 29 70 58 19 64 76 68 95 88  8 68 92 62 35 54 31 56 18
 68  9]


In [108]:
np.percentile(arr,50)  #ortasından alır. tam orta sayıyı alır. 50th percentile, Q2,median

51.0

In [109]:
np.percentile(arr,25)   #25th percentile, Q1 

29.0

In [110]:
np.percentile(arr,75)   #75th percentile, Q3

69.5

berryyyyy